SmartPenWebApp/Controllers/DbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;

using SmartSignWebApp.ViewModels;

namespace SmartSignWebApp.Controllers
{
    public class DbController : Controller
    {
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {
            var items = await DocumentDBRepository<AdminViewModel>.GetItemsAsync(
                //d => d.Id == id
                d => true
                );
            ViewBag.Title = "Document List";
            return View(items);
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<ActionResult> SearchIndexAsync(AdminViewModel model)
        {
            var items = await DocumentDBRepository<AdminViewModel>.GetItemsAsync(
                //d => d.Id == id
                d =>  true
                //d.fName.ToString().Contains(model.fName) &&
                );
            ViewBag.Title = "Document List";
            return View(items);
        }

        [ActionName("Create")]
        public IActionResult Create()
        {
            return RedirectToAction("Admin", "App");
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(AdminViewModel item)
        {
            if (ModelState.IsValid)
            {
                await DocumentDBRepository<AdminViewModel>.UpdateItemAsync(item.Id, item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        [ActionName("Edit")]
        public async Task<ActionResult> EditAsync(string id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return null;
            }

            AdminViewModel item = await DocumentDBRepository<AdminViewModel>.GetItemAsync(id);
            if (item == null)
            {
                //return HttpNotFound();
                return null;
            }

            return View(item);
        }

    }
}

SmartPenWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>DocSign: @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-pencil-square"></i> DocSign</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">@*&#9776;*@<i class="fa fa-ellipsis-v" style="color:#9d9d9d"></i> </button>
            </div>
            <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Admin">Request Signature</a></li>
                    <li><a asp-controller="Db" asp-action="Index">View Documents</a></li>
                    @*<li><a asp-controller="App" asp-action="Client">Client</a></li>*@
                </ul>
            </div>
        </header>
    </div>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">Michael McNamara - Industry Project</div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    @*Create a place in the layout that a view can use to insert optional content(scripts).
            has a matching section in a view page

        <script src="~/js/admin.js"></script>
    *@
    @RenderSection("scripts", false)
</body>
</html>