SmartPenWebApp/Controllers/AppController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SmartSignWebApp.Services;
using SmartSignWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Neosmartpen.Net.Protocol.v1;
using SmartSignWebApp.PenConnector;
using Microsoft.Azure.Documents.Client;
using Microsoft.Azure.Documents;
using System.Net;
using Newtonsoft.Json;

using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using SmartSignWebApp.PDF;
using System.Drawing;

namespace SmartSignWebApp.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        ////public static PenConnector.PenConnector _penConnector { get; set; }
        private readonly PenConnector.PenConnector _penConnector;
        private readonly DocumentClient _client;

        private readonly string DatabaseName = Environment.GetEnvironmentVariable("DATABASEID");
        private readonly string CollectionName = Environment.GetEnvironmentVariable("COLLECTIONID");
        //private AdminViewModel model { get; set; }

        //hosting env for paths
        private IHostingEnvironment _hostingEnvironment;

        /* Use a constructor to inject the services needed
         * */
        public AppController(IMailService mailService, IHostingEnvironment environment, PenCommV1Callbacks penConnector, DocumentClient client)
        {
            _client = client;
            _penConnector = penConnector as PenConnector.PenConnector;
            _penConnector.ClearImage();
            _hostingEnvironment = environment;
            _mailService = mailService;
            //_penConnector = new PenConnector.PenConnector(_hostingEnvironment);


        }



        /* Actions: These actions are executed when the url path matches
         * The view returned is based on the cshtml page with the same name
         * as the action, in the views folder.
         */
        public IActionResult Index() {
            CloudBlobContainer container = GetCloudBlobContainer();
            ViewBag.Success = container.CreateIfNotExistsAsync().Result;
            System.Console.WriteLine(ViewBag.Success);
            ViewBag.Title = "Home ";
            return View();
        }

        public IActionResult Admin()
        {
            ViewBag.Title = "Request Signature";
            ViewBag.UploadStatus = "Upload";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AdminAsync(AdminViewModel model)
        {
            ViewBag.Title = "Request Signature";
            /*Validation:
             * ModelState - Uses data annotations to validate the model
             */
            if (ModelState.IsValid) {
                //Create record  
                model.isSigned = false;
                _mailService.SendNewDocument(
                        await DocumentDBRepository<AdminViewModel>.CreateDocumentIfNotExists(model), 
                        _hostingEnvironment);
                ;
                //await CreateDocumentIfNotExists(DatabaseName, CollectionName, model);
                //_mailService.SendNewDocument(model, _hostingEnvironment );
                ViewBag.UserMessage = "Document sent";
                ModelState.Clear();
            }
            ViewBag.UploadStatus = "Upload";
            return RedirectToAction("Index", "Db");
        }

        public async Task<IActionResult> Client(string id)
        {
            AdminViewModel model = await DocumentDBRepository<AdminViewModel>.GetItemAsync(id);
            ViewBag.DocName = model.DocName;
            ViewBag.Id = model.Id;
            if (!model.isSigned)
            {
                ViewBag.Title = model.fName+ " " +model.lName+" you are required to sign: " + model.DocName;
                ViewBag.pdfURL = GetBlobSasUri(model.DocGuid);
                return View();
            }
            else
            {
                ViewBag.Title = "Welcome back " + model.fName + ", you have signed " + model.DocName;
                ViewBag.pdfURL = GetBlobSasUri(model.SignedDocGuid);
                return View("DrawSignature");
            }
        }


        public async Task<IActionResult> DrawSignature()
        {

            var id = Request.Path.ToString().Substring(Request.Path.ToString().LastIndexOf('/') + 1);
            AdminViewModel model = await DocumentDBRepository<AdminViewModel>.GetItemAsync(id);

            // _penConnector.DrawSignature();           
            Bitmap tempBitmap = new Bitmap(800, 1131);
            Graphics g = Graphics.FromImage(tempBitmap);
            g.Clear(Color.Transparent);
            g.Dispose();
            //
            _penConnector.DrawSignature(model.Id, tempBitmap);


            PDFCombine.CombinePdfPng(GetBlobSasUri(model.DocGuid), model.Id, _hostingEnvironment);

            if (System.IO.File.Exists(System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "img/pen/"+model.Id+".png"))) {
                System.IO.File.Delete(System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "img/pen/" + model.Id + ".png"));
            }

            string uploadName = System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "pdf/ImageCombine.pdf");
            FileStream fs = new FileStream(uploadName, FileMode.Open, FileAccess.Read);
            model.isSigned = true;
            model.SignedDocGuid = UploadBlob(fs, model.DocName);
            await DocumentDBRepository<AdminViewModel>.UpdateItemAsync(model.Id, model);
            ViewBag.Title = "Thank you for signing";
            ViewBag.Id = model.Id;
            ViewBag.pdfURL = GetBlobSasUri(model.SignedDocGuid);
            _mailService.DocumentSigned(model, _hostingEnvironment);
            return View();
        }

        public async Task<IActionResult> ConnectPen()
        {           
            _penConnector.connectPen();
            _penConnector.ClearImage();

            ViewBag.Title = "Connecting...";
            var id = Request.Path.ToString().Substring(Request.Path.ToString().LastIndexOf('/') + 1);
            AdminViewModel model = await DocumentDBRepository<AdminViewModel>.GetItemAsync(id);

            ViewBag.pdfURL = GetBlobSasUri(model.DocGuid);
            ViewBag.DocName = model.DocName;
            ViewBag.Id = model.Id;
            return View("Client");
            //return new EmptyResult();
        }


        public async Task<IActionResult> ClearImage()
        {

            if (_penConnector != null)
            {
                _penConnector.ClearSignature();
                _penConnector.ClearImage();
            }

            var id = Request.Path.ToString().Substring(Request.Path.ToString().LastIndexOf('/') + 1);
            AdminViewModel model = await DocumentDBRepository<AdminViewModel>.GetItemAsync(id);

            ViewBag.pdfURL = GetBlobSasUri(model.DocGuid);
            ViewBag.Id = model.Id;
            ViewBag.DocName = model.DocName;

            return View("Client");
            
        }


        //Start of file upload methods
        [HttpPost]
        public IActionResult UploadFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                ViewBag.UploadStatus = "Upload";
                ViewBag.Message = "No File Selected";
                return View("Admin");//RedirectToAction("Admin");
            }
            string pdfContentType = "application/pdf";
            if (file.ContentType != pdfContentType)
            {
                ViewBag.UploadStatus = "Upload";
                ViewBag.Message = "Wrong format, PDF only";
                return View("Admin");//RedirectToAction("Admin");
            }
            else {
                ViewBag.UploadStatus = "UploadSuccess";
                ViewBag.Message = "Upload Accepted";

               

                /*
                string fileName = Path.GetFileName(file.FileName);
                ViewBag.documentName = fileName;
                var blobName = UploadBlob(file);
                */

                string docName = Path.GetFileName(file.FileName);
                ViewBag.docName = docName;

                ViewBag.docGuid = UploadBlob(file, docName);

                //ViewBag.docGuid = UploadBlob(file, docName);
                Console.WriteLine("File name: " + ViewBag.docName);
                Console.WriteLine("Document ID: " + ViewBag.docGuid);
                /*
                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/uploads/"+fileName
                           );

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                */

                return View("Admin");//RedirectToAction("Admin");
            }
        }

        private CloudBlobContainer GetCloudBlobContainer()
        {
            //Environment.GetEnvironmentVariable("BLOB_CONNECTION_STRING");
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                Environment.GetEnvironmentVariable("BLOB_CONNECTION_STRING"));
            //CloudConfigurationManager.GetSetting("<storageaccountname>_AzureStorageConnectionString"));
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("pdf-container");
            return container;
        }

        public string UploadBlob(FileStream fs, string fileName)
        {

SmartPenWebApp/Controllers/PenController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace SmartSignWebApp.Controllers
{
    public class PenController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private PenConnector.PenConnector _penConnector;


        public PenController(IHostingEnvironment environment)
        {
            this._hostingEnvironment = environment;
            _penConnector = new PenConnector.PenConnector(_hostingEnvironment);
            _penConnector.ClearImage();
        }
        public IActionResult ConnectPen()
        {
            _penConnector.connectPen();

            ViewBag.Title = "Connecting...";
            return RedirectToAction("Client","App");
        }

        public IActionResult DisconnectPen() {

            if (_penConnector != null) {

                _penConnector.disconnected();

            }

            ViewBag.Title = "Disconnecting...";
            return RedirectToAction("Client", "App");
        }

        public IActionResult ClearImage()
        {

            if (_penConnector != null)
            {
                _penConnector.ClearImage();
            }

            ViewBag.Title = "Clearing Image...";
            return RedirectToAction("Client", "App");
        }
        
    }
}

SmartPenWebApp/Views/App/Admin.cshtml
@model AdminViewModel
@*{
        ViewBag.Title = "Admin";
    }*@

@*This section is added to the scripts section are in the _Layout.cshtml*@
<script>
    uploadedFile = ("@(ViewBag.UploadStatus)" == "UploadSuccess" ) ? true:false;
</script>

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/admin.js"></script>
}


<div id="uploadForm">


    <div class="well">

        @{
            String uploadStatus = ViewBag.UploadStatus;
            await Html.RenderPartialAsync(uploadStatus);
        }

       
        <form method="post" asp-controller="app" asp-action="AdminAsync">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="DocName">Document Name:</label>
                <input asp-for="DocName" type="text" value="@ViewBag.docName" class="form-control formDisable" />
                <span asp-validation-for="DocName"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocGuid">Document ID:</label>
                <input asp-for="DocGuid" type="text" value="@ViewBag.docGuid" class="form-control formDisable" />
                <span asp-validation-for="DocGuid"></span>
            </div>

            <div class="form-group">
                <label asp-for="fName">First Name:</label>
                <input asp-for="fName" type="text" class="form-control formToggle" />
                <span asp-validation-for="fName"></span>
            </div>
            <div class="form-group">
                <label asp-for="lName">Last Name:</label>
                <input asp-for="lName" type="text" class="form-control formToggle" />
                <span asp-validation-for="lName"></span>
            </div>
            <div class="form-group">
                <label ToolTip="The address of the signatory" asp-for="signatoryEmail">Signatory Email:</label>
                <input ToolTip="The address of the signatory" asp-for="signatoryEmail" type="email" class="form-control formToggle" />
                <span asp-validation-for="signatoryEmail"></span>
            </div>
            <div class="form-group">
                <label ToolTip="When a document is signed notify this address" asp-for="notifyEmail">Notify Email:</label>
                <input ToolTip="When a document is signed notify this address" asp-for="notifyEmail" type="email" class="form-control formToggle" />
                <span asp-validation-for="notifyEmail"></span>
            </div>

            <div class="form-group">
                <label ToolTip="Add an optional message" asp-for="message">Message:</label>
                <textarea asp-for="message" rows="4" class="form-control formToggle"></textarea>
                <span asp-validation-for="message"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary formToggle"><i class="fa fa-envelope"></i> Send Document</button>
            </div>
        </form>
    </div>
</div> 

SmartPenWebApp/Views/App/Client.cshtml
@*{
        //ViewBag.Title = "Client";
    }*@

@section scripts {
    <script src="~/js/client.js"></script>
}
@*
    <div style="position: relative; height:1131px; width:800px; ">
        <div id="backdrop" style="z-index: 1; position: absolute; top: 0px; left: 0px;">
            <embed src="@ViewBag.pdfURL" width="800" height="1131" type='application/pdf' />
        </div>
        <div id="curtain" style="z-index: 2; position: absolute; top: 0px; left: 0px; background-image:url(/curtain.png);background-position:100px 200px;">
            <div style="z-index:1001"><img id="sig" src="~/img/pen/web.png"></div>
        </div>
    </div>*@

<div class="well">
    <div>
        <label>Download</label>
        <a href="@ViewBag.pdfURL" download="@ViewBag.DocName">Download</a>
        <br />



        @*
        <div style="z-index:1000"><embed src="@ViewBag.pdfURL" width="800" height="1131" /></div>
        <div style="z-index:1001"><img id="sig" src="~/img/pen/web.png"></div>*@


        <form asp-controller="App" asp-action="ConnectPen/@ViewBag.Id">
            <label>Connect</label>
            <button id="connectButton" type="submit">Connect SmartPen</button>
        </form>
        @*<form asp-controller="Pen" asp-action="DisconnectPen">
        <label>Disconnect</label>
        <button id="disconnectButton" type="submit">Disconnect SmartPen</button>
        form>*@
        <form asp-controller="App" asp-action="ClearImage/?@ViewBag.Id">
            <label>ClearImage</label>
            <button type="submit">ClearImage</button>
        </form>

        @Html.ActionLink("Sign", "DrawSignature", "App", new { id = ViewBag.Id })

        <form asp-controller="App" asp-action="DrawSignature/@ViewBag.Id">
            <label>Sign Document</label>
            <button type="submit">Sign</button>
        </form>

        <br />

    </div>
</div>

@*<div style="position:absolute;height:100px;width:100px;background-color:Yellow;" onclick="showHideElement('Iframe1');">click me</div>
    <div style="position:absolute;z-index:100;background-color:Green;height:100px;width:100px;margin-left:200px;"></div>
*@
<div style="position:absolute;z-index:20;margin-left:0px;">
    <img id="sig" src="~/img/pen/web.png" style="border:0px solid black">
    <iframe visible="true" id="Iframe1" height="100" width="100" runat="server" frameborder="0" scrolling="auto"></iframe>
</div>

<div style="position:absolute;z-index:10;margin-left:0px;">
    <iframe visible="true" id="ipdf" src="@ViewBag.pdfURL" width="800" height="1131" runat="server" frameborder="0" scrolling="auto"></iframe>
</div>

SmartPenWebApp/Views/App/DrawSignature.cshtml
@*{
        //ViewBag.Title = "Client";
    }*@

@section scripts {
    <script src="~/js/client.js"></script>
}

<div class="well">
    <div>
        <label>Download</label>
        <a href="@ViewBag.pdfURL" download="@ViewBag.DocName">Download</a>
        <br />


    </div>
</div>


<div style="position:absolute;z-index:10;margin-left:0px;">
    <iframe visible="true" id="ipdf" src="@ViewBag.pdfURL" width="800" height="1131" runat="server" frameborder="0" scrolling="auto"></iframe>
</div>

SmartPenWebApp/Views/App/Index.cshtml
@{
    //razor code
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html>
<head>
    <title>Smart Sign @ViewBag.Title</title>
</head>
<body>
    <h1>Smart Sign</h1>
</body>
</html>

SmartPenWebApp/Views/App/Upload.cshtml
<form asp-controller="app" asp-action="UploadFile" method="post"
      enctype="multipart/form-data">

    <input type="file" name="file" />
    <button type="submit">Upload PDF</button>
    <br />
    <span>@ViewBag.Message  @ViewBag.fileName</span>
</form>

@{
}

SmartPenWebApp/Views/App/UploadSuccess.cshtml
<span><label>@ViewBag.Message:</label>  @ViewBag.fileName</span>
<br />


@{
}